### ISSUE TITLE
Module stubs should support relative links

### ISSUE THREAD

**Issue by alexmuller** [alphagov/spotlight#488]
The following JSON snippet fails validation:

```
  "relatedPages": {
    "transaction": {
      "title": "Apply for a UK visa",
      "url" : "/apply-uk-visa"
    }
  },
```

I think I'd be ok with this passing.

**Comment by easternbloc** [comment]
We don't validate JSON in spotlight anymore this is a job for :trumpet::trumpet::trumpet: www.github.com/alphagov/stagecraft
