### ISSUE TITLE
Styling on web traffic data is broken

### ISSUE THREAD

**Issue by easternbloc** [alphagov/spotlight#997]
https://www.gov.uk/performance/web-traffic

**Comment by jcbashdown** [comment]
Thanks Ben, we've just moved to the new infrastructure. Had some problems around routing assets we thought were resolved so it may be related.

How's Croydon life? Sum it up in a GIF.

**Comment by easternbloc** [comment]
Cool should be an easy fix then.

Here is a gif: 

![](http://media.giphy.com/media/XPZZeIyVlgwdG/giphy.gif)
